ERROR - 2024-03-16 04:36:16 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 PRIMARY KEY(`username`)
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_gener...' at line 7 in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\codenighter\app\Database\Migrations\2024-03-15-150829_Users.php(35): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): App\Database\Migrations\Users->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-16 04:37:55 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 PRIMARY KEY(`username`)
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_gener...' at line 7 in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\codenighter\app\Database\Migrations\2024-03-15-150829_Users.php(35): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): App\Database\Migrations\Users->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
CRITICAL - 2024-03-16 05:16:21 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "vw_register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('vw_register.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('vw_register', [], true)
 3 APPPATH\Controllers\Register.php(11): view('vw_register')
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 05:16:23 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "vw_register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('vw_register.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('vw_register', [], true)
 3 APPPATH\Controllers\Register.php(11): view('vw_register')
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 05:31:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 13:26:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 13:26:38 --> mysqli_sql_exception: Table 'crud_data.crud_data' doesn't exist in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `cr...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cr...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cr...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cr...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:26:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'crud_data.crud_data' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:26:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'crud_data.crud_data' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$jvqneL5MptB3CqXf63bigONlV6a2FViG/wBqKWBsy.f.JkS5KC/F2\', \'Fahmil Ulum\', \'2024-03-16 13:26:38\', \'2024-03-16 13:26:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$jvqneL5MptB3CqXf63bigONlV6a2FViG/wBqKWBsy.f.JkS5KC/F2\', \'Fahmil Ulum\', \'2024-03-16 13:26:38\', \'2024-03-16 13:26:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:26:38 --> [Caused by] mysqli_sql_exception: Table 'crud_data.crud_data' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$jvqneL5MptB3CqXf63bigONlV6a2FViG/wBqKWBsy.f.JkS5KC/F2\', \'Fahmil Ulum\', \'2024-03-16 13:26:38\', \'2024-03-16 13:26:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$jvqneL5MptB3CqXf63bigONlV6a2FViG/wBqKWBsy.f.JkS5KC/F2\', \'Fahmil Ulum\', \'2024-03-16 13:26:38\', \'2024-03-16 13:26:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$jvqneL5MptB3CqXf63bigONlV6a2FViG/wBqKWBsy.f.JkS5KC/F2\', \'Fahmil Ulum\', \'2024-03-16 13:26:38\', \'2024-03-16 13:26:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 13:26:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 13:27:06 --> mysqli_sql_exception: Table 'crud_data.crud_data' doesn't exist in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `cr...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cr...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cr...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cr...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:27:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'crud_data.crud_data' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:27:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'crud_data.crud_data' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$rV2dQzlMk3g2Mv2THVASneKiR3QNDmeeYyAfsm5cARbrFBp3A1.6K\', \'Fahmil Ulum\', \'2024-03-16 13:27:06\', \'2024-03-16 13:27:06\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$rV2dQzlMk3g2Mv2THVASneKiR3QNDmeeYyAfsm5cARbrFBp3A1.6K\', \'Fahmil Ulum\', \'2024-03-16 13:27:06\', \'2024-03-16 13:27:06\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:27:06 --> [Caused by] mysqli_sql_exception: Table 'crud_data.crud_data' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$rV2dQzlMk3g2Mv2THVASneKiR3QNDmeeYyAfsm5cARbrFBp3A1.6K\', \'Fahmil Ulum\', \'2024-03-16 13:27:06\', \'2024-03-16 13:27:06\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$rV2dQzlMk3g2Mv2THVASneKiR3QNDmeeYyAfsm5cARbrFBp3A1.6K\', \'Fahmil Ulum\', \'2024-03-16 13:27:06\', \'2024-03-16 13:27:06\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$rV2dQzlMk3g2Mv2THVASneKiR3QNDmeeYyAfsm5cARbrFBp3A1.6K\', \'Fahmil Ulum\', \'2024-03-16 13:27:06\', \'2024-03-16 13:27:06\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `crud_data` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-16 13:30:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:30:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:30:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$CS8MEs1JKLUPxlf4jpFoX.m1F6bGWzGAbBpCPKZ7l7vz6W8ifQ7i2\', \'Fahmil Ulum\', \'2024-03-16 13:30:51\', \'2024-03-16 13:30:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$CS8MEs1JKLUPxlf4jpFoX.m1F6bGWzGAbBpCPKZ7l7vz6W8ifQ7i2\', \'Fahmil Ulum\', \'2024-03-16 13:30:51\', \'2024-03-16 13:30:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:30:51 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$CS8MEs1JKLUPxlf4jpFoX.m1F6bGWzGAbBpCPKZ7l7vz6W8ifQ7i2\', \'Fahmil Ulum\', \'2024-03-16 13:30:51\', \'2024-03-16 13:30:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$CS8MEs1JKLUPxlf4jpFoX.m1F6bGWzGAbBpCPKZ7l7vz6W8ifQ7i2\', \'Fahmil Ulum\', \'2024-03-16 13:30:51\', \'2024-03-16 13:30:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$CS8MEs1JKLUPxlf4jpFoX.m1F6bGWzGAbBpCPKZ7l7vz6W8ifQ7i2\', \'Fahmil Ulum\', \'2024-03-16 13:30:51\', \'2024-03-16 13:30:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 13:33:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 13:37:38 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:37:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:37:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Pu12bhMob0shJfaRMJLlGub3d3YOUp1YhrMRXhdudxzgDQ9krd7zS\', \'Fahmil Ulum\', \'2024-03-16 13:37:38\', \'2024-03-16 13:37:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Pu12bhMob0shJfaRMJLlGub3d3YOUp1YhrMRXhdudxzgDQ9krd7zS\', \'Fahmil Ulum\', \'2024-03-16 13:37:38\', \'2024-03-16 13:37:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:37:38 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Pu12bhMob0shJfaRMJLlGub3d3YOUp1YhrMRXhdudxzgDQ9krd7zS\', \'Fahmil Ulum\', \'2024-03-16 13:37:38\', \'2024-03-16 13:37:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Pu12bhMob0shJfaRMJLlGub3d3YOUp1YhrMRXhdudxzgDQ9krd7zS\', \'Fahmil Ulum\', \'2024-03-16 13:37:38\', \'2024-03-16 13:37:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Pu12bhMob0shJfaRMJLlGub3d3YOUp1YhrMRXhdudxzgDQ9krd7zS\', \'Fahmil Ulum\', \'2024-03-16 13:37:38\', \'2024-03-16 13:37:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-16 13:40:52 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:40:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:40:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$zX/Q/519AHqxlZBQrCNTeu7SqgJjEPXjREQcDBIk2aM7t.YQ2Gz16\', \'Fahmil Ulum\', \'2024-03-16 13:40:52\', \'2024-03-16 13:40:52\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$zX/Q/519AHqxlZBQrCNTeu7SqgJjEPXjREQcDBIk2aM7t.YQ2Gz16\', \'Fahmil Ulum\', \'2024-03-16 13:40:52\', \'2024-03-16 13:40:52\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:40:52 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$zX/Q/519AHqxlZBQrCNTeu7SqgJjEPXjREQcDBIk2aM7t.YQ2Gz16\', \'Fahmil Ulum\', \'2024-03-16 13:40:52\', \'2024-03-16 13:40:52\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$zX/Q/519AHqxlZBQrCNTeu7SqgJjEPXjREQcDBIk2aM7t.YQ2Gz16\', \'Fahmil Ulum\', \'2024-03-16 13:40:52\', \'2024-03-16 13:40:52\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$zX/Q/519AHqxlZBQrCNTeu7SqgJjEPXjREQcDBIk2aM7t.YQ2Gz16\', \'Fahmil Ulum\', \'2024-03-16 13:40:52\', \'2024-03-16 13:40:52\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-16 13:55:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:55:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:55:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$HV9cK8mibtIiaAyZARfoz.uBUWoJq7bah2PxQ907yszP1CrIDRXS6\', \'Fahmil Ulum\', \'2024-03-16 13:55:04\', \'2024-03-16 13:55:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$HV9cK8mibtIiaAyZARfoz.uBUWoJq7bah2PxQ907yszP1CrIDRXS6\', \'Fahmil Ulum\', \'2024-03-16 13:55:04\', \'2024-03-16 13:55:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:55:04 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$HV9cK8mibtIiaAyZARfoz.uBUWoJq7bah2PxQ907yszP1CrIDRXS6\', \'Fahmil Ulum\', \'2024-03-16 13:55:04\', \'2024-03-16 13:55:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$HV9cK8mibtIiaAyZARfoz.uBUWoJq7bah2PxQ907yszP1CrIDRXS6\', \'Fahmil Ulum\', \'2024-03-16 13:55:04\', \'2024-03-16 13:55:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$HV9cK8mibtIiaAyZARfoz.uBUWoJq7bah2PxQ907yszP1CrIDRXS6\', \'Fahmil Ulum\', \'2024-03-16 13:55:04\', \'2024-03-16 13:55:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 13:55:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 13:55:17 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 13:55:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:55:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$3UX4MaZpNilx4YHIAqiBX.MThaFH/H2FX0bJOumCAMgYUK3i7ST9u\', \'Fahmil \', \'2024-03-16 13:55:17\', \'2024-03-16 13:55:17\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$3UX4MaZpNilx4YHIAqiBX.MThaFH/H2FX0bJOumCAMgYUK3i7ST9u\', \'Fahmil \', \'2024-03-16 13:55:17\', \'2024-03-16 13:55:17\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 13:55:17 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$3UX4MaZpNilx4YHIAqiBX.MThaFH/H2FX0bJOumCAMgYUK3i7ST9u\', \'Fahmil \', \'2024-03-16 13:55:17\', \'2024-03-16 13:55:17\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$3UX4MaZpNilx4YHIAqiBX.MThaFH/H2FX0bJOumCAMgYUK3i7ST9u\', \'Fahmil \', \'2024-03-16 13:55:17\', \'2024-03-16 13:55:17\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$3UX4MaZpNilx4YHIAqiBX.MThaFH/H2FX0bJOumCAMgYUK3i7ST9u\', \'Fahmil \', \'2024-03-16 13:55:17\', \'2024-03-16 13:55:17\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-16 14:13:17 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 PRIMARY KEY(`username`)
) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_gener...' at line 7 in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\codenighter\app\Database\Migrations\2024-03-15-150829_Users.php(35): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): App\Database\Migrations\Users->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-16 14:26:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 14:26:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 14:26:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$SZ/7mejK93Mx9auDKWOgCOvDcZ5eDnk0svJhZju7z6R8TrwG9AxIa\', \'Fahmil \', \'2024-03-16 14:26:04\', \'2024-03-16 14:26:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$SZ/7mejK93Mx9auDKWOgCOvDcZ5eDnk0svJhZju7z6R8TrwG9AxIa\', \'Fahmil \', \'2024-03-16 14:26:04\', \'2024-03-16 14:26:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 14:26:04 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$SZ/7mejK93Mx9auDKWOgCOvDcZ5eDnk0svJhZju7z6R8TrwG9AxIa\', \'Fahmil \', \'2024-03-16 14:26:04\', \'2024-03-16 14:26:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$SZ/7mejK93Mx9auDKWOgCOvDcZ5eDnk0svJhZju7z6R8TrwG9AxIa\', \'Fahmil \', \'2024-03-16 14:26:04\', \'2024-03-16 14:26:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$SZ/7mejK93Mx9auDKWOgCOvDcZ5eDnk0svJhZju7z6R8TrwG9AxIa\', \'Fahmil \', \'2024-03-16 14:26:04\', \'2024-03-16 14:26:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 14:26:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 14:26:21 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 14:26:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 14:26:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$QBMjZdIThUYK00trX6OyG.ibihmrXXwSMHbh.iyC1k8MMQA.VHMIm\', \'Fahmil \', \'2024-03-16 14:26:21\', \'2024-03-16 14:26:21\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$QBMjZdIThUYK00trX6OyG.ibihmrXXwSMHbh.iyC1k8MMQA.VHMIm\', \'Fahmil \', \'2024-03-16 14:26:21\', \'2024-03-16 14:26:21\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 14:26:21 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$QBMjZdIThUYK00trX6OyG.ibihmrXXwSMHbh.iyC1k8MMQA.VHMIm\', \'Fahmil \', \'2024-03-16 14:26:21\', \'2024-03-16 14:26:21\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$QBMjZdIThUYK00trX6OyG.ibihmrXXwSMHbh.iyC1k8MMQA.VHMIm\', \'Fahmil \', \'2024-03-16 14:26:21\', \'2024-03-16 14:26:21\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$QBMjZdIThUYK00trX6OyG.ibihmrXXwSMHbh.iyC1k8MMQA.VHMIm\', \'Fahmil \', \'2024-03-16 14:26:21\', \'2024-03-16 14:26:21\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-16 14:43:44 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 14:43:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 14:43:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Bqa89PdOtLnHOJ6cXtplCehWuItsnahxuAYS583A.YsfZARaWMM2u\', \'Fahmil \', \'2024-03-16 14:43:44\', \'2024-03-16 14:43:44\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Bqa89PdOtLnHOJ6cXtplCehWuItsnahxuAYS583A.YsfZARaWMM2u\', \'Fahmil \', \'2024-03-16 14:43:44\', \'2024-03-16 14:43:44\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 14:43:44 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Bqa89PdOtLnHOJ6cXtplCehWuItsnahxuAYS583A.YsfZARaWMM2u\', \'Fahmil \', \'2024-03-16 14:43:44\', \'2024-03-16 14:43:44\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Bqa89PdOtLnHOJ6cXtplCehWuItsnahxuAYS583A.YsfZARaWMM2u\', \'Fahmil \', \'2024-03-16 14:43:44\', \'2024-03-16 14:43:44\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$Bqa89PdOtLnHOJ6cXtplCehWuItsnahxuAYS583A.YsfZARaWMM2u\', \'Fahmil \', \'2024-03-16 14:43:44\', \'2024-03-16 14:43:44\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 22:08:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:09:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:09:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:09:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:09:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:12:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:12:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:12:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:13:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:13:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:13:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:13:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 22:13:31 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 22:13:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:13:31 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$KdgVqbd2l31/ufrtEw3s6ucPr9wKM/Yl9pOzHK/HUH/AaNuWBateq\', \'Fahmil Ulum\', \'2024-03-16 22:13:31\', \'2024-03-16 22:13:31\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$KdgVqbd2l31/ufrtEw3s6ucPr9wKM/Yl9pOzHK/HUH/AaNuWBateq\', \'Fahmil Ulum\', \'2024-03-16 22:13:31\', \'2024-03-16 22:13:31\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:13:31 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$KdgVqbd2l31/ufrtEw3s6ucPr9wKM/Yl9pOzHK/HUH/AaNuWBateq\', \'Fahmil Ulum\', \'2024-03-16 22:13:31\', \'2024-03-16 22:13:31\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$KdgVqbd2l31/ufrtEw3s6ucPr9wKM/Yl9pOzHK/HUH/AaNuWBateq\', \'Fahmil Ulum\', \'2024-03-16 22:13:31\', \'2024-03-16 22:13:31\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$KdgVqbd2l31/ufrtEw3s6ucPr9wKM/Yl9pOzHK/HUH/AaNuWBateq\', \'Fahmil Ulum\', \'2024-03-16 22:13:31\', \'2024-03-16 22:13:31\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 22:15:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:17:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 22:17:58 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 22:17:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:17:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$dK/iMc/Xt/kU9QirTY7N7OWAHQXibHAqKxGxm1iZePeb2IhvNuXNK\', \'fahmil\', \'2024-03-16 22:17:58\', \'2024-03-16 22:17:58\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$dK/iMc/Xt/kU9QirTY7N7OWAHQXibHAqKxGxm1iZePeb2IhvNuXNK\', \'fahmil\', \'2024-03-16 22:17:58\', \'2024-03-16 22:17:58\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:17:58 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$dK/iMc/Xt/kU9QirTY7N7OWAHQXibHAqKxGxm1iZePeb2IhvNuXNK\', \'fahmil\', \'2024-03-16 22:17:58\', \'2024-03-16 22:17:58\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$dK/iMc/Xt/kU9QirTY7N7OWAHQXibHAqKxGxm1iZePeb2IhvNuXNK\', \'fahmil\', \'2024-03-16 22:17:58\', \'2024-03-16 22:17:58\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'fahmil\', \'$2y$10$dK/iMc/Xt/kU9QirTY7N7OWAHQXibHAqKxGxm1iZePeb2IhvNuXNK\', \'fahmil\', \'2024-03-16 22:17:58\', \'2024-03-16 22:17:58\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 22:18:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:18:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:18:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-16 22:23:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 22:24:00 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 22:24:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:24:00 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$GIJCLG0r306LCN7ROWzsfuHalYi3.TqIvsnqElIqiPa1HYp/g/aDG\', \'Fahmil Ulum\', \'2024-03-16 22:24:00\', \'2024-03-16 22:24:00\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$GIJCLG0r306LCN7ROWzsfuHalYi3.TqIvsnqElIqiPa1HYp/g/aDG\', \'Fahmil Ulum\', \'2024-03-16 22:24:00\', \'2024-03-16 22:24:00\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:24:00 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$GIJCLG0r306LCN7ROWzsfuHalYi3.TqIvsnqElIqiPa1HYp/g/aDG\', \'Fahmil Ulum\', \'2024-03-16 22:24:00\', \'2024-03-16 22:24:00\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$GIJCLG0r306LCN7ROWzsfuHalYi3.TqIvsnqElIqiPa1HYp/g/aDG\', \'Fahmil Ulum\', \'2024-03-16 22:24:00\', \'2024-03-16 22:24:00\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$GIJCLG0r306LCN7ROWzsfuHalYi3.TqIvsnqElIqiPa1HYp/g/aDG\', \'Fahmil Ulum\', \'2024-03-16 22:24:00\', \'2024-03-16 22:24:00\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-16 22:27:03 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 22:27:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:27:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$uVCQUeJt.elVCJQU7KDBUuSnHNqpTVUwRs8FhRutXt/80ytVuNUDq\', \'Fahmil Ulum\', \'2024-03-16 22:27:03\', \'2024-03-16 22:27:03\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$uVCQUeJt.elVCJQU7KDBUuSnHNqpTVUwRs8FhRutXt/80ytVuNUDq\', \'Fahmil Ulum\', \'2024-03-16 22:27:03\', \'2024-03-16 22:27:03\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:27:03 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$uVCQUeJt.elVCJQU7KDBUuSnHNqpTVUwRs8FhRutXt/80ytVuNUDq\', \'Fahmil Ulum\', \'2024-03-16 22:27:03\', \'2024-03-16 22:27:03\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$uVCQUeJt.elVCJQU7KDBUuSnHNqpTVUwRs8FhRutXt/80ytVuNUDq\', \'Fahmil Ulum\', \'2024-03-16 22:27:03\', \'2024-03-16 22:27:03\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$uVCQUeJt.elVCJQU7KDBUuSnHNqpTVUwRs8FhRutXt/80ytVuNUDq\', \'Fahmil Ulum\', \'2024-03-16 22:27:03\', \'2024-03-16 22:27:03\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 22:27:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 22:27:18 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codenighter\app\Controllers\Register.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): App\Controllers\Register->process()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-16 22:27:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:27:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$qjS7O1LBQpSc2UpZt/5jEOwEXSR.rE0D/7JQWfR6tgMYDGNvupm8O\', \'Fahmil Ulum\', \'2024-03-16 22:27:18\', \'2024-03-16 22:27:18\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$qjS7O1LBQpSc2UpZt/5jEOwEXSR.rE0D/7JQWfR6tgMYDGNvupm8O\', \'Fahmil Ulum\', \'2024-03-16 22:27:18\', \'2024-03-16 22:27:18\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-16 22:27:18 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$qjS7O1LBQpSc2UpZt/5jEOwEXSR.rE0D/7JQWfR6tgMYDGNvupm8O\', \'Fahmil Ulum\', \'2024-03-16 22:27:18\', \'2024-03-16 22:27:18\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$qjS7O1LBQpSc2UpZt/5jEOwEXSR.rE0D/7JQWfR6tgMYDGNvupm8O\', \'Fahmil Ulum\', \'2024-03-16 22:27:18\', \'2024-03-16 22:27:18\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (\'12fahmil\', \'$2y$10$qjS7O1LBQpSc2UpZt/5jEOwEXSR.rE0D/7JQWfR6tgMYDGNvupm8O\', \'Fahmil Ulum\', \'2024-03-16 22:27:18\', \'2024-03-16 22:27:18\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `password`, `name`, `created_at`, `updated_at`) VALUES (:username:, :password:, :name:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Register.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Register->process()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-16 22:27:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-16 22:28:00 --> mysqli_sql_exception: Table 'users' already exists in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\codenighter\app\Database\Migrations\2024-03-15-150829_Users.php(35): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): App\Database\Migrations\Users->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2024-03-16 22:31:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
